# Generated by Django 3.1.6 on 2021-03-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0005_auto_20210329_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (4, 'Drama'), (3, 'Sci-fi'), (2, 'Komedy'), (0, 'Other')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('stars', models.PositiveSmallIntegerField(choices=[(2, 'not bad'), (1, 'disaster'), (3, 'not bad not good'), (5, 'awesome'), (4, 'good')], default=0)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.film')),
            ],
        ),
    ]
