# Generated by Django 3.1.6 on 2021-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0007_auto_20210329_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Other'), (1, 'Horror'), (2, 'Komedy'), (4, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(3, 'not bad not good'), (4, 'good'), (2, 'not bad'), (5, 'awesome'), (1, 'disaster')], default=3),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('films', models.ManyToManyField(to='filmyweb.Film')),
            ],
        ),
    ]
